# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dataexchange.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dataexchange.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x61taexchange.proto\x12\x0c\x64\x61taexchange\"\x07\n\x05\x45mpty\"\x1c\n\tArrowData\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"\x16\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t2\x91\x01\n\x10\x41rrowDataService\x12>\n\x0cGetArrowData\x12\x13.dataexchange.Empty\x1a\x17.dataexchange.ArrowData0\x01\x12=\n\rSendArrowData\x12\x17.dataexchange.ArrowData\x1a\x11.dataexchange.Ack(\x01\x42!Z\x1fproto/dataexchange;dataexchangeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dataexchange_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037proto/dataexchange;dataexchange'
  _globals['_EMPTY']._serialized_start=36
  _globals['_EMPTY']._serialized_end=43
  _globals['_ARROWDATA']._serialized_start=45
  _globals['_ARROWDATA']._serialized_end=73
  _globals['_ACK']._serialized_start=75
  _globals['_ACK']._serialized_end=97
  _globals['_ARROWDATASERVICE']._serialized_start=100
  _globals['_ARROWDATASERVICE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
